- hosts: localhost

  vars:
    package_list_json: "{{ lookup('file', 'packages.json') | from_json }}"

  tasks:

  - name: Setting package list as a fact
    set_fact: package_list="{{ package_list_json }}"


- hosts: all
  strategy: linear
  remote_user: strivr-admin
  gather_facts: no
  become: true
  become_user: root

  pre_tasks:
  - name: Check disk space for gen1 MDs.
    include_role: 
      name: check_disk_space

  - name: install packages and enforce version constarints
    include_role:
      name: package_install

  - name: install packages and enforce version constarints
    include_role:
      name: update_packages

  - name: get the kernel version on the remote device
    shell: "apt-cache policy linux-image-generic |grep Installed |awk '{print $2}'"
    register: kernel_version

  - name: compareinstalled version of limux-image-generic against desired version
    debug: msg="{{ hostvars['localhost'].package_list['kernel'][0].Version }} vs {{ kernel_version.stdout }}"

  - name: upgrade kernel on remote hosts
    include_role:
      name: update_kernel
    when: kernel_version.stdout != hostvars['localhost'].package_list['kernel'][0].Version

  - name: restart the MD
    include_role:
      name: restartmd
    when: kernel_version.stdout != hostvars['localhost'].package_list['kernel'][0].Version

  - name: apply time fix and run setup
    include_role:
      name: fix_time   

  - name: run setup
    include_role:
      name: setup

  post_tasks:
  - name: Cleanup after running
    include_role:
      name: cleanup
 
